name: windows

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/windows.yml
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**
  pull_request:
    paths:
      - .github/workflows/windows.yml
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      FTP_SERVER: ${{ secrets.FTP_SERVER }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.2

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Add custom conan repo
      run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_UNIT_TESTS=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Tests
      working-directory: ${{github.workspace}}/build
      shell: bash
      run:  |
            ctest --rerun-failed --output-on-failure -C $BUILD_TYPE
            echo "SERVER: [" 
            echo $FTP_SERVER
            echo ${{ env.FTP_SERVER }}
            echo "]"

    - name: Deploy
      if: ${{ matrix.build_type == 'Release' }}
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        dry-run: true
